### ISSUE TITLE
Rajout Panel admin

### ISSUE THREAD

**Issue by thirax** [thirax/Projet-WSDB#14]
Rajouter un **bonton**  qui se **voit**  que quand on  est **loguer en  admin** qui nous fait aller sur  une page ou on  peut  gere les  bd ;)   si ta  le temps mon  choux  @SlaughtyY Low  prioritée

**Comment by SlaughtyY** [comment]
Travail réalisé. Vérifie si c'est le résultat que tu souhaites.

**Comment by thirax** [comment]
Super génial ça marche :) 💯 
je close l'issue(si  bug je réouvre)
