### ISSUE TITLE
Dupplication d'entité

### ISSUE THREAD

**Issue by SlaughtyY** [thirax/Projet-WSDB#25]
Duplication de l'utilisateur lorsqu'on rafraîchit la page.

![image](https://user-images.githubusercontent.com/64400217/83340842-35a99600-a2dd-11ea-89e6-390d4608fc65.png)

![gif](https://media1.tenor.com/images/d3f50e7dc11fd6ed15845e6b845c835c/tenor.gif?itemid=16825265)

**Comment by thirax** [comment]
d'apres @SlaughtyY  chemain   qui foutreaitlamerde

**Comment by thirax** [comment]
Hmm j'arrive  pas a recrée le  bug

**Comment by Wquarks** [comment]
La duplication n'existe plus

**Comment by thirax** [comment]
@Wquarks    comment  tu  a  fait, qu'a tu fait ?  pourquoi  y a vait t'il le bug ?
