### ISSUE TITLE
Game mecanique

### ISSUE THREAD

**Issue by thirax** [thirax/Projet-WSDB#29]
mecanique de jeux faire que la page jeux fonctione est soit jouable

**Comment by thirax** [comment]
je majoute

**Comment by Wquarks** [comment]
je pense que l'on devra rajouter une page pour patienter que le deuxieme joueur s'ajoute. De cette manière, on permet d'avoir obligatoirement deux joueur sur une page de jeux.

**Comment by Wquarks** [comment]
Le jeux est jouable :D
