### ISSUE TITLE
Refresh bouton game

### ISSUE THREAD

**Issue by Wquarks** [thirax/Projet-WSDB#31]
Faire en sorte que le bouton game refresh la page sans nous faire retourner à l'index.

Voici le code actuel dans Jeuxapp.java qui est à modifier : 
````
 public Result jouer(String pseudo,Boolean value) {
        return ok(views.html.messagetempo.render(Jeux.jouercoup(pseudo,value)));
		
    }
````

**Comment by thirax** [comment]
fixer par la en rajoutant des var comme un pork https://github.com/thirax/Projet-WSDB/commit/6c242015f673438d9cee86b66cb8c33291d809c1
