### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by thirax** [thirax/Projet-WSDB#9]
https://github.com/thirax/Projet-WSDB/blob/c9c19d54f6cc1a19d8427f9a2f5c14e7fc302eea/Projet/app/controllers/Userapp.java#L46

on check  si il  y a un cookie donc que l'user est identifier mais si l'utilisateur n'existe plus le  mec garde le cookie il  va essayer de trouver l'user lier au cookie
donc soit on check que le cookie est valide soit on  fait une expiration

**Comment by thirax** [comment]
metre un cookies par defgaut avec un champ  type et des rep comme genr userloguer  usergesse et  no  kooked

**Comment by Wquarks** [comment]
Le cookie n'étais pas pris en compte directement après la connexion et donné un id=0. De base il fallait cliquer sur le bouton profil pour réactualiser. Alors j'ai automatiser l'action avec le code suivant : 
`<script type="text/javascript">
function red(){
        window.location.href = "/profile";
}
</script>`
puis on insert au niveau du num d'id le code suivant:
`ID: 
	@{if ( userProfils.id != 0) userProfils.id else <script type="text/javascript">red();</script>}`

**Comment by thirax** [comment]
Merci wiwi mais il y a encor un autre bug a réglée

**Comment by thirax** [comment]
le truc ces que ta fait un scripte pour résoudre le problème la meilleur solution serait de la faire coter ser veurs mias  ça marche
